### ISSUE TITLE
[TODO] Check interoperability with widget toolkits

### ISSUE THREAD

**Issue by vaiorabbit** [vaiorabbit/ruby-opengl#1]
-   FXRuby ( http://www.fxruby.org/ )
-   Ruby-GNOME2 ( http://ruby-gnome2.sourceforge.jp/ )
-   Tk
-   Ref.: Ruby Programming/GUI Toolkit Modules
  -   http://en.wikibooks.org/wiki/Ruby_Programming/GUI_Toolkit_Modules

**Comment by cedlemo** [comment]
hi @vaiorabbit,

I am a contributor to Ruby-Gnome2 and I have to test and  create samples for the GtkGLArea widget. The owner of the Ruby-gnome2 project has decided to focus on your project for the openGL ruby implementation. So it is likely that I will send you a couple of issues/requests soon.

Regards

**Comment by vaiorabbit** [comment]
Hi @cedlemo,

Thank you for using this library. Any improvement proposals will be welcome.
You can even make incompatible changes because I haven't heard any adoption news about this project :-( .

**Comment by vaiorabbit** [comment]
Recent progress:

*   Ruby-GNOME2 https://github.com/ruby-gnome2/ruby-gnome2 : (Thanks : @cedlemo )
    *   https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/misc/gtkglarea1.rb
    *   https://github.com/ruby-gnome2/ruby-gnome2/blob/master/gtk3/sample/misc/gtkglarea2.rb

*   ruby-sdl2 https://github.com/ohai/ruby-sdl2 :
    *   https://github.com/vaiorabbit/ruby-opengl/blob/master/sample/SDL2/testgl_ruby-sdl2.rb

*   sld2r https://github.com/mirichi/sdl2r : (Thanks : @mirichi)
    *   https://gist.github.com/mirichi/f33008c2767dbd28438e
    *   https://twitter.com/mirichi/status/646510946991472640

*   FXRuby https://github.com/larskanis/fxruby/ :
    *   Unfortunately, I cannot build and run it on Mac OS X.
