### ISSUE TITLE
Windows MSYS2 Ruby 2.4.1-2 (x64): GLFW library load error

### ISSUE THREAD

**Issue by mrlukaszfuszara** [vaiorabbit/ruby-opengl#27]
This error is connected with precompiled library from http://www.glfw.org/download.html , compiled for MSYS2 is loading but can't show window (Expression: window != NULL). 
Since Ruby 2.4 all Windows builds are using MSYS2 as compilation environment.

**Comment by vaiorabbit** [comment]
Hi.

I don't have enough time to reproduce your problem now, and I don't know much about MSYS2 (sorry).

In general, if you use ruby built on MSYS2, you must make sure that all shared libraries (.dll) you are going to use are built on MSYS2.
And current GLFW package for Windows (glfw-3.2.1.bin.WIN64.zip) does not contain DLLs for MSYS2.

    $ cd ~/Downloads/glfw-3.2.1.bin.WIN64
    $ ll
        -rw-r--r--@ 1 foo  staff  928  8 18  2016 COPYING.txt
        drwxr-xr-x@ 3 foo  staff  102  8 18  2016 docs
        drwxr-xr-x@ 3 foo  staff  102  8 18  2016 include
        drwxrwxr-x@ 5 foo  staff  170  8 18  2016 lib-mingw-w64
        drwxrwxr-x@ 5 foo  staff  170  8 18  2016 lib-vc2012
        drwxrwxr-x@ 5 foo  staff  170  8 18  2016 lib-vc2013
        drwxrwxr-x@ 5 foo  staff  170  8 18  2016 lib-vc2015
