### ISSUE TITLE
glLightfv fails

### ISSUE THREAD

**Issue by bookface** [vaiorabbit/ruby-opengl#28]
glLightfv(GL_LIGHT0, GL_DIFFUSE, [1.0, 1.0, 1.0, 1.0])
fails with "can't convert Array into Integer (TypeError)"

**Comment by larskanis** [comment]
You must use
```
glLightfv(GL_LIGHT0, GL_DIFFUSE, [1.0, 1.0, 1.0, 1.0].pack("f*"))
```

This gem doesn't provide Ruby style automatisms for parameter handling. Value arrays must be passed as strings therefore.
